version: "3.9"

services:
  yii2-app:
    build: .
    container_name: yii2-app
    ports:
      - "9090:80"  # localhost:9090 mengarah ke container port 80
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/web
